name: Build Release

permissions:
  contents: read
  security-events: write
  actions: read

on:
  push:
    branches: [main]

jobs:
  check-and-build:
    name: Check & Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.16.1

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "20"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run build
        run: pnpm build:prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: ./frontend/dist
          retention-days: 30

      - name: Build with bundle analysis
        run: pnpm build:prod --analyze

      - name: Upload bundle analysis
        uses: actions/upload-artifact@v4
        with:
          name: bundle-analysis
          path: ./frontend/dist/stats.html
          retention-days: 7
